include:
- ./func/*
kind: ArchiveUploadSpec
name: func-9EPI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: notification-list-fn-5077cb3f-1438-424a-96a2-6c1805417175
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: notification-list-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-9EPI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-11-29T20:27:11Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: notification-list-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: notification-list-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_all_notifications
    packageref:
      name: notification-list-fn-5077cb3f-1438-424a-96a2-6c1805417175
      namespace: default
  requestsPerPod: 10000
  resources: {}
