apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: notification-list-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: notification-list-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /notifications/get_all
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /notifications/get_all
